num = int(input('Digite um numero entre 1 e 9999: '))
u = (num//1 % 10)
d = (num//10 % 10)
c =(num//100 % 10)
m = (num//1000 % 10)
print('unidade: {}'.format(u))
print('Dezena: {}'.format(d))
print('Centena: {}'.format(c))
print('Milhar {}'.format(m))
